/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/anki/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bible book statistics */
        get: operations["get_books_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arc/top-places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get top 10 places by time spent over last 6 months */
        get: operations["get_top_places_stats_endpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/faith/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get unified faith statistics for last 30 days */
        get: operations["get_faith_daily_stats_endpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/faith/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get today's unified faith statistics */
        get: operations["get_faith_today_stats_endpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/faith/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get unified faith statistics for last 12 weeks */
        get: operations["get_faith_weekly_stats_endpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check endpoint */
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Aggregated statistics for a collection of books */
        AggregateStats: {
            book_stats: components["schemas"]["BookStats"][];
            label: string;
            /** Format: int64 */
            learning_passages: number;
            /** Format: int64 */
            learning_verses: number;
            /** Format: int64 */
            mature_passages: number;
            /** Format: int64 */
            mature_verses: number;
            /** Format: int64 */
            suspended_passages: number;
            /** Format: int64 */
            suspended_verses: number;
            /** Format: int64 */
            unseen_passages: number;
            /** Format: int64 */
            unseen_verses: number;
            /** Format: int64 */
            young_passages: number;
            /** Format: int64 */
            young_verses: number;
        };
        /** @description Complete Bible statistics report */
        BibleStats: {
            new_testament: components["schemas"]["AggregateStats"];
            old_testament: components["schemas"]["AggregateStats"];
        };
        /** @description Statistics for a single Bible book */
        BookStats: {
            book: string;
            /** Format: int64 */
            learning_passages: number;
            /** Format: int64 */
            learning_verses: number;
            /** Format: int64 */
            mature_passages: number;
            /** Format: int64 */
            mature_verses: number;
            /** Format: int64 */
            suspended_passages: number;
            /** Format: int64 */
            suspended_verses: number;
            /** Format: int64 */
            unseen_passages: number;
            /** Format: int64 */
            unseen_verses: number;
            /** Format: int64 */
            young_passages: number;
            /** Format: int64 */
            young_verses: number;
        };
        /** @description Error response */
        ErrorResponse: {
            error: string;
        };
        /** @description Faith statistics for multiple days with summary */
        FaithDailyStats: {
            days: components["schemas"]["FaithDayStats"][];
            summary: components["schemas"]["FaithDailySummary"];
        };
        /** @description Summary statistics for faith activities over a period */
        FaithDailySummary: {
            /** Format: double */
            anki_average_minutes_per_day: number;
            anki_days_studied: number;
            /** Format: int64 */
            anki_net_progress: number;
            /** Format: double */
            anki_total_hours: number;
            /** Format: int64 */
            anki_total_lost_passages: number;
            /** Format: int64 */
            anki_total_matured_passages: number;
            /** Format: double */
            anki_total_minutes: number;
            /** Format: double */
            average_minutes_per_day: number;
            days_with_any_activity: number;
            /** Format: double */
            prayer_average_minutes_per_day: number;
            prayer_days_studied: number;
            /** Format: double */
            prayer_total_hours: number;
            /** Format: double */
            prayer_total_minutes: number;
            /** Format: double */
            reading_average_minutes_per_day: number;
            reading_days_studied: number;
            /** Format: double */
            reading_total_hours: number;
            /** Format: double */
            reading_total_minutes: number;
            total_days: number;
            /** Format: double */
            total_hours: number;
            /** Format: double */
            total_minutes: number;
        };
        /** @description Combined faith statistics for a single day */
        FaithDayStats: {
            /**
             * Format: int64
             * @description Cumulative count of mature passages at end of day
             */
            anki_cumulative_passages: number;
            /**
             * Format: int64
             * @description Number of passages that were lost on this day
             */
            anki_lost_passages: number;
            /**
             * Format: int64
             * @description Number of passages that matured on this day
             */
            anki_matured_passages: number;
            /**
             * Format: double
             * @description Anki study time in minutes
             */
            anki_minutes: number;
            /** @description Date in YYYY-MM-DD format */
            date: string;
            /**
             * Format: double
             * @description Prayer time in minutes
             */
            prayer_minutes: number;
            /**
             * Format: double
             * @description Bible reading time in minutes
             */
            reading_minutes: number;
        };
        /** @description Combined faith statistics for today */
        FaithTodayStats: {
            /**
             * Format: double
             * @description Anki study time in minutes
             */
            anki_minutes: number;
            /**
             * Format: double
             * @description Prayer time in minutes
             */
            prayer_minutes: number;
            /**
             * Format: double
             * @description Bible reading time in minutes
             */
            reading_minutes: number;
            /**
             * Format: double
             * @description Total hours across all activities
             */
            total_hours: number;
            /**
             * Format: double
             * @description Total minutes across all activities
             */
            total_minutes: number;
        };
        /** @description Combined faith statistics for a single week */
        FaithWeekStats: {
            /**
             * Format: int64
             * @description Cumulative count of mature passages at end of week
             */
            anki_cumulative_passages: number;
            /**
             * Format: int64
             * @description Number of passages that were lost during this week
             */
            anki_lost_passages: number;
            /**
             * Format: int64
             * @description Number of passages that matured during this week
             */
            anki_matured_passages: number;
            /**
             * Format: double
             * @description Anki study time in minutes
             */
            anki_minutes: number;
            /**
             * Format: double
             * @description Time spent at church in minutes
             */
            at_church_minutes: number;
            /**
             * Format: double
             * @description Prayer time in minutes
             */
            prayer_minutes: number;
            /**
             * Format: double
             * @description Bible reading time in minutes
             */
            reading_minutes: number;
            /** @description Week start date in YYYY-MM-DD format */
            week_start: string;
        };
        /** @description Faith statistics for multiple weeks with summary */
        FaithWeeklyStats: {
            summary: components["schemas"]["FaithWeeklySummary"];
            weeks: components["schemas"]["FaithWeekStats"][];
        };
        /** @description Summary statistics for faith activities over a weekly period */
        FaithWeeklySummary: {
            /** Format: double */
            anki_average_minutes_per_week: number;
            /** Format: int64 */
            anki_net_progress: number;
            /** Format: double */
            anki_total_hours: number;
            /** Format: int64 */
            anki_total_lost_passages: number;
            /** Format: int64 */
            anki_total_matured_passages: number;
            /** Format: double */
            anki_total_minutes: number;
            anki_weeks_studied: number;
            /** Format: double */
            average_minutes_per_week: number;
            /** Format: double */
            church_average_minutes_per_week: number;
            /** Format: double */
            church_total_hours: number;
            /** Format: double */
            church_total_minutes: number;
            church_weeks_attended: number;
            /** Format: double */
            prayer_average_minutes_per_week: number;
            /** Format: double */
            prayer_total_hours: number;
            /** Format: double */
            prayer_total_minutes: number;
            prayer_weeks_studied: number;
            /** Format: double */
            reading_average_minutes_per_week: number;
            /** Format: double */
            reading_total_hours: number;
            /** Format: double */
            reading_total_minutes: number;
            reading_weeks_studied: number;
            /** Format: double */
            total_hours: number;
            /** Format: double */
            total_minutes: number;
            total_weeks: number;
            weeks_with_any_activity: number;
        };
        /** @description Health check response */
        HealthCheck: {
            service: string;
            status: string;
        };
        /** @description Statistics for a single place showing time spent */
        PlaceStats: {
            /**
             * Format: double
             * @description Total hours spent at this place
             */
            hours: number;
            /** @description Name of the place */
            place_name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_books_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bible book statistics retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleStats"];
                };
            };
            /** @description Unauthorized - invalid or missing API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_top_places_stats_endpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Top 10 places by hours spent over last 6 months retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceStats"][];
                };
            };
            /** @description Unauthorized - invalid or missing API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_faith_daily_stats_endpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unified faith statistics for last 30 days retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaithDailyStats"];
                };
            };
            /** @description Unauthorized - invalid or missing API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_faith_today_stats_endpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Today's unified faith statistics retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaithTodayStats"];
                };
            };
            /** @description Unauthorized - invalid or missing API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_faith_weekly_stats_endpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unified faith statistics for last 12 weeks retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaithWeeklyStats"];
                };
            };
            /** @description Unauthorized - invalid or missing API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheck"];
                };
            };
        };
    };
}
